---
{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "labels": {
      "app": "site-operator",
      "k8s-app": "site-operator"
    },
    "name": "site-operator",
    "namespace": "operators"
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "site-operator",
        "k8s-app": "site-operator"
      }
    },
    "template": {
      "metadata": {
        "labels": {
          "app": "site-operator",
          "k8s-app": "site-operator"
        }
      },
      "spec": {
        "containers": [
          {
            "env": [
              {
                "name": "MIX_ENV",
                "value": "prod"
              },
              {
                "name": "BONNY_POD_NAME",
                "valueFrom": {
                  "fieldRef": {
                    "fieldPath": "metadata.name"
                  }
                }
              },
              {
                "name": "BONNY_POD_NAMESPACE",
                "valueFrom": {
                  "fieldRef": {
                    "fieldPath": "metadata.namespace"
                  }
                }
              },
              {
                "name": "BONNY_POD_IP",
                "valueFrom": {
                  "fieldRef": {
                    "fieldPath": "status.podIP"
                  }
                }
              },
              {
                "name": "BONNY_POD_SERVICE_ACCOUNT",
                "valueFrom": {
                  "fieldRef": {
                    "fieldPath": "spec.serviceAccountName"
                  }
                }
              }
            ],
            "image": "eu.gcr.io/code-supply/site-operator:e86fcab",
            "name": "site-operator",
            "resources": {
              "limits": {
                "cpu": "50m",
                "memory": "100Mi"
              },
              "requests": {
                "cpu": "10m",
                "memory": "48Mi"
              }
            },
            "securityContext": {
              "allowPrivilegeEscalation": false,
              "readOnlyRootFilesystem": true,
              "runAsNonRoot": true,
              "runAsUser": 65534
            }
          }
        ],
        "serviceAccountName": "site-operator"
      }
    }
  }
}
---
{
  "apiVersion": "apiextensions.k8s.io/v1beta1",
  "kind": "CustomResourceDefinition",
  "metadata": {
    "labels": {
      "app": "site-operator",
      "k8s-app": "site-operator"
    },
    "name": "affiliatesites.site-operator.code.supply"
  },
  "spec": {
    "additionalPrinterColumns": [
      {
        "JSONPath": ".spec.domains",
        "description": "Domain names of the website",
        "name": "domains",
        "type": "string"
      },
      {
        "JSONPath": ".metadata.creationTimestamp",
        "description": "CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\n      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
        "name": "Age",
        "type": "date"
      }
    ],
    "group": "site-operator.code.supply",
    "names": {
      "kind": "AffiliateSite",
      "plural": "affiliatesites",
      "shortNames": [
        "as"
      ],
      "singular": "affiliatesite"
    },
    "scope": "Cluster",
    "version": "v1"
  }
}
---
{
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "kind": "ClusterRole",
  "metadata": {
    "labels": {
      "app": "site-operator",
      "k8s-app": "site-operator"
    },
    "name": "site-operator"
  },
  "rules": [
    {
      "apiGroups": [
        "apiextensions.k8s.io"
      ],
      "resources": [
        "customresourcedefinitions"
      ],
      "verbs": [
        "*"
      ]
    },
    {
      "apiGroups": [
        "site-operator.code.supply"
      ],
      "resources": [
        "affiliatesites"
      ],
      "verbs": [
        "*"
      ]
    },
    {
      "apiGroups": [
        ""
      ],
      "resources": [
        "namespaces"
      ],
      "verbs": [
        "get"
      ]
    },
    {
      "apiGroups": [
        ""
      ],
      "resources": [
        "namespaces",
        "secrets",
        "services"
      ],
      "verbs": [
        "create",
        "delete"
      ]
    },
    {
      "apiGroups": [
        "apps"
      ],
      "resources": [
        "deployments"
      ],
      "verbs": [
        "create",
        "get",
        "update",
        "delete"
      ]
    },
    {
      "apiGroups": [
        "networking.istio.io"
      ],
      "resources": [
        "gateways",
        "virtualservices"
      ],
      "verbs": [
        "get",
        "create",
        "delete"
      ]
    },
    {
      "apiGroups": [
        "cert-manager.io"
      ],
      "resources": [
        "certificates"
      ],
      "verbs": [
        "get",
        "create",
        "delete"
      ]
    },
    {
      "apiGroups": [
        "rbac.authorization.k8s.io"
      ],
      "resources": [
        "rolebindings"
      ],
      "verbs": [
        "get",
        "create",
        "delete"
      ]
    }
  ]
}
---
{
  "apiVersion": "v1",
  "kind": "ServiceAccount",
  "metadata": {
    "labels": {
      "app": "site-operator",
      "k8s-app": "site-operator"
    },
    "name": "site-operator",
    "namespace": "operators"
  }
}
---
{
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "kind": "ClusterRoleBinding",
  "metadata": {
    "labels": {
      "app": "site-operator",
      "k8s-app": "site-operator"
    },
    "name": "site-operator"
  },
  "roleRef": {
    "apiGroup": "rbac.authorization.k8s.io",
    "kind": "ClusterRole",
    "name": "site-operator"
  },
  "subjects": [
    {
      "kind": "ServiceAccount",
      "name": "site-operator",
      "namespace": "operators"
    }
  ]
}

