apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/0
      value: --dns01-recursive-nameservers="8.8.8.8:53"
  target:
    kind: Deployment
    labelSelector: app=cert-manager
- path: workload-identity.yaml
  target:
    kind: ServiceAccount
    name: cert-manager
